site_name: RaspiDevelopment
nav: 
    - Главная: 'index.md'
    - Raspbian: 
        - 'RORW_Raspberry4.md' 
        - 'WriteFolder.md'
        - 'SetUpQt.md'
        - 'SetUpBluetooth.md'
        - 'SetUpScreenAndFixStyles.md'
        - 'SetUpUART.md'
        - 'SetUpTwoScreens.md'
    - BU:
        - 'SetUp_compiler.md'

use_directory_urls: false

theme:  readthedocs

    
